### ISSUE TITLE
Missing semicolon in last line of `diagnostic.js`

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/mongoose-crud-diagnostic#20]

**Comment by RDegnen** [comment]
@MattB-GA-Boston fixed

**Comment by gaand** [comment]
@RDegnen Hey Ross.  Would you please post the commit hash for this fix?  Thanks.

**Comment by RealWeeks** [comment]
Resolved in commit ab48bb9b26c79d324c66ac8d43d99dc13e9b31d4 by @RDegnen

**Comment by RealWeeks** [comment]
Closing for @RDegnen
