### ISSUE TITLE
Wrong URL for database

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/mongoose-crud-diagnostic#21]
Per instructions, should be `mongoose-crud-diagnostic` in `diagnostic.js`, not `mongoose-crud`

**Comment by RDegnen** [comment]
@MattB-GA-Boston fixed

**Comment by RealWeeks** [comment]
@RDegnen cite your commits bro

**Comment by RealWeeks** [comment]
resolved in commit 4769545004a9b330ad734d539cb2bff8d9ed407c by @RDegnen

**Comment by RealWeeks** [comment]
Closing for Ross
